### ISSUE TITLE
dcache project products are not published in maven central

### ISSUE THREAD

**Issue by jcalcote** [dCache/oncrpc4j#108]
We've been using the same version of oncrpc4j for some time now. Because of this, we've had the oncrpc4j dependencies we use cached in our local artifact server. Yesterday I went to https://mvnrepository.com/repos/central to find the latest version - the pom file insert for using version 3.3.2 are shown there as:

```
<!-- https://mvnrepository.com/artifact/org.dcache/oncrpc4j-core -->
<dependency>
    <groupId>org.dcache</groupId>
    <artifactId>oncrpc4j-core</artifactId>
    <version>3.3.2</version>
</dependency>
```

However, there is (currently) no dcache directory under https://repo.maven.apache.org/maven2/org/ at maven central. There is also no dcache directory under https://repo1.maven.org/maven2/org/.

This must be an oversight. I _can_ build oncrpc4j-core locally and upload the products to my artifact server, but I don't think you intend for users to do this, right?

<img width="158" alt="image" src="https://github.com/user-attachments/assets/ccf9b1c6-07c7-4e6a-9d8f-616211981468">

**Comment by jcalcote** [comment]
AH! I just noticed this note at maven central:

<img width="714" alt="image" src="https://github.com/user-attachments/assets/a67ae711-89e4-4e33-a24d-11906c479ff3">

Why does dcache use its own custom repository? Why _not_ use the common central repos?

**Comment by jcalcote** [comment]
Ok - so the problem is that 3.3.2 is being advertised as the latest version of the oncrpc4j-core module, but that version is not in your own repository - only 3.3.1 is available. Someone just forgot to upload it.

**Comment by kofemann** [comment]
Usually, we mirror all external dependencies to a local one to able ti build even if central is not available or artifact is removed (yeah we have seen this). Thus, there was ni real need to push to maven central, though we have an account there. I will try to find some time to change that.

**Comment by kofemann** [comment]
Actually, the packages are available on our repo:

https://download.dcache.org/nexus/#browse/browse:releases:org%2Fdcache%2Foncrpc4j-core%2F3.3.2

**Comment by jcalcote** [comment]
Thanks everyone.

**Comment by jcalcote** [comment]
Closing

**Comment by kofemann** [comment]
The latest 3.4.2 release is publisched into maven central
