### ISSUE TITLE
conservative buffer allocation in Xdr constructor leads to huge memory consumption for async io

### ISSUE THREAD

**Issue by radai-rosenblatt** [dCache/oncrpc4j#31]
rpc calls allocate ~0.5MB of buffer:
```java
new Xdr(Xdr.MAX_XDR_SIZE)
```
this, combined with a large number of pending async IO resulting in a lot of heap space being used.

**Comment by radai-rosenblatt** [comment]
i tried changing Xdr.endDecoding() to do trim() instead of simply flip() to try and reclaim some heap space after encoding is done. it didnt work, i dont know why. 

even if it would have worked, i feel the better solution is to start the buffer smaller (1K ?) and get larger ones as space runs out ?

**Comment by kofemann** [comment]
:+1:  Makes sense

**Comment by kofemann** [comment]
resolved by  e14094e4fdfbfd80d67a7423c90f7ca2a83859a7
