### ISSUE TITLE
add a fat-jar artifact of oncrpc4j-core + dependencies for use as an rpcbind server

### ISSUE THREAD

**Issue by radai-rosenblatt** [dCache/oncrpc4j#36]
this is useful for developers working on OSs where there's no native portmap service to be found (windows) or the existing rpcbind server is dysfunctional (mac osx). 

given a "fat jar" it would be relatively easy to run a portmap server by issuing:

`java -cp fat.jar org.dcache.xdr.portmap.OncRpcbindServer`

which is also easier to use in service definition files.

**Comment by radai-rosenblatt** [comment]
im willing to do this, if you guys are ok with the concept

**Comment by kofemann** [comment]
Hi Radai,

I think the idea is good. You can add an jar with dependencies and main-class org.dcache.xdr.portmap.OncRpcbindServer, then it will be much easier to use:

java -jar rpcbind.jar

oncrpc4j-spring uses a similar, but has it's own module.

**Comment by kofemann** [comment]
closed by 410e87cb44ed72e556c051077fee5bf3c716b719
