### ISSUE TITLE
Portmapper : owner unspecified when dumping rpcbs ...

### ISSUE THREAD

**Issue by jfcjm** [dCache/oncrpc4j#56]
A call through  GenericPortmapClient to  client.dump agains a fresh OncRpcbindServer instance returns
the following :
prog: 100000, vers: 2, netid: tcp, addr: 0.0.0.0.0.111, owner: unspecified
prog: 100000, vers: 2, netid: udp, addr: 0.0.0.0.0.111, owner: unspecified

here owner is "unspecified" while it is initialized to "superuser" in   OncRpcbindServer constructor

**Comment by jfcjm** [comment]
This seems related to last line of the constructor `public rpcb(mapping old)` in `org.dcache.xdr.portmap.rpcb` : 
```

 public rpcb(mapping old) {
        _prog = old.getProg();
        _vers = old.getVers();
        _netid = IpProtocolType.toString(old.getProt());
        _addr = netid.toString(old.getPort());
        _owner = "unspecified";
    }
```

**Comment by jfcjm** [comment]
See PR https://github.com/dCache/oncrpc4j/pull/57

**Comment by kofemann** [comment]
@pepijnve can you provide a test case?

**Comment by pepijnve** [comment]
Not a self-contained one I'm afraid. Try using the client with any server that doesn't support rpcbind v4, but does support portmap and you'll get the error. If you compare [mapping#xdrDecode](https://github.com/dCache/oncrpc4j/blob/80c1b526ae3568a3bca3ad028ab55156ca51d57b/oncrpc4j-core/src/main/java/org/dcache/oncrpc4j/portmap/mapping.java#L73) with the definition in https://tools.ietf.org/html/rfc1833 you'll see that it's simply incorrect and cannot work correctly.

**Comment by kofemann** [comment]
Hm, it server does not supports rpcbind v2, the it have to talk v2. I will check and try to come up with an test case. Thanks for reporting!

**Comment by pepijnve** [comment]
FYI, I got this error with an old 7-mode NetApp filer.

**Comment by jenschurchill** [comment]
I'm getting this on my windows 10 and ubuntu 18.04 machines, along with some other servers I'v tested on.
nfs4j 0.17 and oncrpc 3.0.0 (it works with 0.16 and 2.7)

**Comment by kofemann** [comment]
@jenschurchill Thanks for update.

**Comment by kofemann** [comment]
@jenschurchill can you elaborate on what behavior you expect and what you get?

**Comment by jenschurchill** [comment]
When creating a server using v. 3, and running `showmount -e localhost`,
I expect the exports to be listed, instead of the server throwing 'XDR stream too short' errors.

The following code is simplified from my existing codebase, but it should be comparable,
I include it to make sure the error isn't on my end; I couldn't find a really good code example elsewhere, so it is strung together from other examples, and seams to work with v. 2.7

    new OncRpcEmbeddedPortmap();

    nfsSvc = new OncRpcSvcBuilder()
        .withPort(port)
        .withTCP()
        .withUDP()
        .withAutoPublish()
        .withServiceName(name)
        .withWorkerThreadIoStrategy()
        .build();

    NFSServerV41 nfs4 = new NFSServerV41.Builder()
        .withOperationFactory(new MDSOperationFactory())
        .withExportFile(exportFile)
        .withVfs(fileSystem)
        .build();

    // Create NFS v3 and mountd servers
    NfsServerV3 nfs3 = new NfsServerV3(exportFile, fileSystem);
    MountServer mountd = new MountServer(exportFile, fileSystem);

    // Register NFS servers at portmap service
    nfsSvc.register(new OncRpcProgram(nfs4_prot.NFS4_PROGRAM, nfs4_prot.NFS_V4), nfs4);
    nfsSvc.register(new OncRpcProgram(nfs3_prot.NFS_PROGRAM, nfs3_prot.NFS_V3), nfs3);
    nfsSvc.register(new OncRpcProgram(mount_prot.MOUNT_PROGRAM, mount_prot.MOUNT_V3), mountd);

    nfsSvc.start();
