### ISSUE TITLE
Xdr#xdrEncodeByteBuffer flips input buffer before using it

### ISSUE THREAD

**Issue by pepijnve** [dCache/oncrpc4j#62]
`Xdr#xdrEncodeByteBuffer` calls `Buffer#flip` on the input parameter before using it. This is rather surprising since `Buffer` based APIs normally use the position and limit of a `Buffer` to communicate which range of data should be used. Calling `flip` on the buffer makes it impossible to use any other position than 0.
Is this intentional or a bug?

**Comment by kofemann** [comment]
The assumption is that buffer is filled outside and then passed to the encode method, like:
```
Xdr xdr = ...;
ButeByffer buf = ...;

but.put(....);
xdr. xdrEncodeByteBuffer(buf);
```

Does it makes sense? To me it works as designed, but documentation is missing of course.

**Comment by pepijnve** [comment]
Typically you work with Buffer as in [WritableByteChannel.html#write](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/WritableByteChannel.html#write(java.nio.ByteBuffer)). In other words, the caller does the flip and the consumer consumes as many bytes as reported by `remaining`.

I can get it to work, it's just a bit surprising and makes certain usages impossible.

**Comment by kofemann** [comment]
Well, if you have a use case, then we can change the behavior. I just check the places where we use it and it's not an issue for as to adjust our code.

**Comment by kofemann** [comment]
@paulmillar What do you think about it? Shall we change the behavior  and if yes, shall we fix it in 3.0 (which I have tagged today)? To it it looks like was a bad design decision to flip in xdrEncodeByteBuffer

**Comment by kofemann** [comment]
@pepijnve Today we have release 3.0.1 which includes desired change.

**Comment by pepijnve** [comment]
That was fast. Thanks!
