### ISSUE TITLE
Failure downloading artifacts

### ISSUE THREAD

**Issue by dkocher** [dCache/oncrpc4j#65]
`Failed to read artifact descriptor for org.dcache:oncrpc4j-core:jar:3.0.1: Could not transfer artifact org.dcache:oncrpc4j-core:pom:3.0.1 from/to dcache releases (https://download.dcache.org/nexus/content/repositories/releases): Failed to transfer file: https://download.dcache.org/nexus/content/repositories/releases/org/dcache/oncrpc4j-core/3.0.1/oncrpc4j-core-3.0.1.pom. Return code is: 500 , ReasonPhrase:javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report `

**Comment by kofemann** [comment]
Thanks for let as know. I hope it fixed now.

**Comment by kofemann** [comment]
dcache.org infrastructure issue. Fixed.
