### ISSUE TITLE
Is Windows' RPC Endpoint Mapper supported?

### ISSUE THREAD

**Issue by umphy** [dCache/oncrpc4j#66]
Hi, I'm very new to RPC. I am trying to convert some old Sun RPC code to Java in order to run on Windows. I was wondering if the Windows Portmapper service (RPC endpoint mapper) is supported by oncrpc4j or do I need to run your Java portmapdaemon?

Sorry for creating an issue for this question, as there is no way for me to message you via GitHub.

**Comment by kofemann** [comment]
AFAK, windows has it's own RPC service which is not compatible with SunRPC. However, I am not an expert in windows. To check compatibility, simply use **rpcinfo** command on any unix/linux box to query RPC service running under windows.

**Comment by umphy** [comment]
I now have a better understanding. Windows RPC is based on DCE RPC, so you are right in saying it is not compatible with Sun RPC.

However, with Windows Server (not desktop), you can install a Windows Role Service called "Services for Network File System" in order to support Unix systems accessing Windows file system via NFS. And since NFS requires Sun RPC compatible portmapper, it will also be available after the the role service is installed.

With Windows desktop, I have found a software (though not free) called haneWin NFS server which provides NFS server (and thus portmapper) functionality to Windows.

Please note that I have yet to test these thoroughly. My progress so far is just to get the RPC server to not complain about unavailable portmapper service.
