### ISSUE TITLE
How to get Port of the registered program

### ISSUE THREAD

**Issue by TaslimAlam** [dCache/oncrpc4j#67]
Hi,

***This is a query and not an issue. ***
I am trying to call RPC in UNIX server, but before actual call in need to look for the port of the program from portmap using program id and version number. 

I have tested  string Length program, and rpcinfo is giving below details : 

   program version netid     address                service    owner
    100000    4    tcp6      ::.0.111               portmapper superuser
    100000    3    tcp6      ::.0.111               portmapper superuser
    100000    4    udp6      ::.0.111               portmapper superuser
    100000    3    udp6      ::.0.111               portmapper superuser
    100000    4    tcp       0.0.0.0.0.111          portmapper superuser
    100000    3    tcp       0.0.0.0.0.111          portmapper superuser
    100000    2    tcp       0.0.0.0.0.111          portmapper superuser
    100000    4    udp       0.0.0.0.0.111          portmapper superuser
    100000    3    udp       0.0.0.0.0.111          portmapper superuser
    100000    2    udp       0.0.0.0.0.111          portmapper superuser
    100000    4    local     /run/rpcbind.sock      portmapper superuser
    100000    3    local     /run/rpcbind.sock      portmapper superuser
       **117    1    tcp       0:0:0:0:0:0:0:0.7.127  -          unknown
       117    1    tcp6      0:0:0:0:0:0:0:0.7.127  -          unknown**

The program is registered with ID 177 and Version 1, But how can i determine the port grammatically.

I have gone through the code and found a class GenericPortmapClient and tried to get the dump.Still i am not getting the port of the program. I have used port 1919 while running server application.

Regards
Taslim Alam

**Comment by kofemann** [comment]
the string ** 0:0:0:0:0:0:0:0.7.127** is your ip address and port. You can use netid#getPort() to get port number:

```
  String uaddr = portmapClient.getPort(117, 1,"tcp");
  int port  = netid.getPort(uaddr);
```

**Comment by TaslimAlam** [comment]
That worked.. Thank you Kofemann for quick response. 👍
