### ISSUE TITLE
Version number of rpc server

### ISSUE THREAD

**Issue by challenger572** [dCache/oncrpc4j#77]
Hi,
I am running multiple rpc process  on the server . Multiple threads are sending request to server .each thread need to identify server process .To establish the connection with rpc . In the code you mentioned one constructor .it will take the parameters port number , version, tcp ,program number . Port number I can able to get using portmapperclient object . How can I get the program version number .because each thread need to access the separate server process . 
Thanks

**Comment by challenger572** [comment]
Hi,
Please give me your suggestions.

**Comment by kofemann** [comment]
There is no an _official_ way to get version number. You either have to ping (send request with proc number NULL) and check the result, or just send the request and check the error code.

**Comment by challenger572** [comment]
Hi
I have a multiple threads in Java code  .threads sending request to rpc server . But multiple process are running 
For example :
Address 1 :
Rpc1 portnum 120 version 2
Rpc2 portnum 130 version 3
Rpc  3 portnum 140 version 4 
Address 2 :
Rpc 4 portnum 150 version 5
Rpc 5 pprtnum 160 version 6.
I will ssh from java code and run the netstat -tap command . I will get the all the details .this way is correct ??

**Comment by kofemann** [comment]
well, if your services register themself in portmap, then you can dump the content of portmap with portmapperclient and will see all programs and versions.

**Comment by challenger572** [comment]
Hi kofemann,
I have a c++ rpc server .I want to generate different version numbers for that c++ rpc server from java ..can I use rpcsvc class .is it possible from your code?
Example :
Program number : 10007
But multiple versions( 2,3,4)
For the same c++ rpc server programme.
100007    2   tcp  38903   c++rpc
    100007    3   tcp 60872  c++rpc
100007.    4 tcp 60987 c++rpc
    Please give me your suggestion regarding this .

**Comment by challenger572** [comment]
Hi kofemann
Please give me your suggestions
