### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by psilly** [dCache/oncrpc4j#80]
Hi, I see that oncrpc4j says it is subject to the LGPL license, but it has a dependency on org.dcache.common:dcache-auth which contains source (such as [DesiredRole.java](https://github.com/dCache/dcache/blob/master/modules/common/src/main/java/org/dcache/auth/DesiredRole.java)) that is under AGPL. I believe that means oncrpc4j must also be licensed under AGPL.

Is there a way to break this dependency, so oncrpc4j can be cleanly under LGPL?

**Comment by kofemann** [comment]
Hi @psilly, Thanks for bringing this up! You are right, looks like we enforce mix of licenses. Though it's  only a  small subset of [dCache code](https://github.com/kofemann/dcache-auth-lite), but this have to be cleaned up anyway.

**Comment by elastifile-danis** [comment]
Hi @kofemann 
Are you going to push it to master at the near future?

**Comment by kofemann** [comment]
actually, I waiting for @psilly to update his PR...

**Comment by psilly** [comment]
Sorry, got busy.. updated the PR.

**Comment by JimSermersheim** [comment]
fixed keyword ordering

**Comment by kofemann** [comment]
fixed with 9f8fde0

**Comment by elastifile-danis** [comment]
@kofemann when are you planning to create a release that includes this fix?

**Comment by kofemann** [comment]
@elastifile-danis the -SNAPSHOT should be already available. I have to check that integration with other components of you system works as well before an official release. Does it work for you?

**Comment by elastifile-danis** [comment]
@kofemann Yep it will do. Thanks allot.

**Comment by kofemann** [comment]
@elastifile-danis The 3.1.0 is released. Thanks!
