### ISSUE TITLE
Expose a constructor for OncRpcClient that takes a OncRpcSvcBuilder

### ISSUE THREAD

**Issue by harrv** [dCache/oncrpc4j#99]
I have a need to supply a `threadPoolSize` to the OncRpcSvcBuilder's `withSelectorThreadPoolSize` method for generated clients.

Is there already a way? If not, I'm happy to provide a PR. I see that in the past that's been done by adding additional constructors to `OncRpcClient.java`. Maybe the most recent time was for [PR 53](/dCache/oncrpc4j/pull/53)? 

Before I give you a PR, I wanted to ask, would it be useful to have a `OncRpcClient` constructor that takes an instance of `OncRpcSvcBuilder` so that we wouldn't need additional constructors every time we wanted to pass in a parameter that isn't already exposed? For example, I only need to limit the size of the `selectorThreadPool` but maybe someone else would need to limit the size of the `workerThreadPool` next month and would need to go through this process again. If one of the constructors took a `OncRpcSvcBuilder` then it could also make sure that everything that is needed for a client is set, like `.withClientMode()` and `.withPort(localPort)`, but otherwise allow the end user to construct the client service with everything else allowed by the builder. 

I'm thinking in my PR I'd leave all of the existing constructors alone (so it would be backward compatible with existing code) but change the one that all of the other's call, making it look like this:

```java
public OncRpcClient(InetSocketAddress socketAddress, int protocol, int localPort, IoStrategy ioStrategy, String serviceName) {
    this(socketAddress, localPort, new OncRpcSvcBuilder()
            .withIpProtocolType(protocol)
            .withIoStrategy(ioStrategy)
            .withServiceName(serviceName));
}
```
and then I'd add this one (called by the one above, but could also be used directly by end users who need it like me):

```java
public OncRpcClient(InetSocketAddress socketAddress, int localPort, OncRpcSvcBuilder builder) {
    _socketAddress = socketAddress;
    _rpcsvc = (builder == null ? new OncRpcSvcBuilder() : builder)
            .withClientMode()
            .withPort(localPort)
            .build();
}
```

I wanted to vet that idea with you before I do the work of committing a PR. It seems like it would prevent additional future churn just to expose additional things that the builder already provides.

Thanks for your help and input.

**Comment by kofemann** [comment]
Looks like a reasonable request. However, the `OncRpcClient` is there just to provide a sensible defaults. If initialization done by the builder, then where is the added value of
`OncRpcClient`?

```java
  var clnt = new OncRpcSvcBuilder()
          .withoutAutoPublish()
          .withTCP()
          .withClientMode()
          .withWorkerThreadIoStrategy()
          .withSelectorThreadPoolSize(1)
          .withWorkerThreadPoolSize(1)
          .withRpcService(new OncRpcProgram(PROGNUM, PROGVER), upper)
          .withSSLContext(sslClientContext)
          .withServiceName("clnt")
          .build();
  clnt.start();

  RpcTransport t = clnt.connect(svc.getInetSocketAddress(IpProtocolType.TCP));
  clntCall = new RpcCall(PROGNUM, PROGVER, new RpcAuthTypeNone(), t);
```

The problem with `OncRpcSvcBuilder` is that it allows to build an invalid service for the client. Maybe a special `OncRpcClientBuilder` will be a better option, that will take care that internally used `OncRpcSvcBuilder` built correctly, something like:

```java
  public class OncRpcClient {
     // package only
     OncRpcClient(OncRpcSvc svc) {...}
  }
  
  public class OncRpcClientBuilder {
     
     svcBuilder = new OncRpcSvcBuilder()
           .withClientMode()
           .withoutAutoPublish()
  
     public OncRpcClientBuilder withSelectorThreadPoolSize(int n) {
          svcBuilder.withSelectorThreadPoolSize(1);
          return this;
     }
     
     public OncRpcClient build() {
         return new OncRpcClient(svcBuilder.build());
     }
  }
```

What do you think?

**Comment by harrv** [comment]
@kofemann Yes, that seems better based on the concern you shared. I had attempted to address that in my proposal by setting `.withClientMode()` on the builder once it was passed to the new constructor, but I'm new to using any of the `dCache` projects so didn't immediately recongnize the other things that are probably server-specific such as auto publish.

Our product hasn't moved to Java 11 yet, so we are still using version oncrpc4j 3.1. If this is a change you'd consider backporting to a 3.1.1 or something, I could try to implement your `OncRpcClientBuilder` idea, but maybe better for you to do it if you're willing, and in the meantime I'll probably need to fork and do a more targeted fix on the 3.1 branch. (Depending on whether you're still doing or taking fixes to 3.1.)

**Comment by kofemann** [comment]
I guess, backport to 3.1 is ok, as long as we don't change the behavior. I will try to add a basic implementation that you can enrich if needed.

**Comment by harrv** [comment]
Thank you!

**Comment by kofemann** [comment]
could you check that commit https://github.com/kofemann/oncrpc4j/commit/42fb509d238e7d9a928993c2ddf9618ce88eb9c7 does what you need

**Comment by harrv** [comment]
That looks great! I think I would also need a corresponding change to jrpcgen.java in the dumpClient() method beginning at about line 1955.

**Comment by kofemann** [comment]
The rpcgen is updated as well.

**Comment by harrv** [comment]
Thank you very much. That looks good to me.

**Comment by kofemann** [comment]
The jars should be online.
